// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_calculate_dist
NumericVector rcpp_calculate_dist(NumericMatrix matrix, int max_dist);
RcppExport SEXP _suppoRt_rcpp_calculate_dist(SEXP matrixSEXP, SEXP max_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< int >::type max_dist(max_distSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calculate_dist(matrix, max_dist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_suppoRt_rcpp_calculate_dist", (DL_FUNC) &_suppoRt_rcpp_calculate_dist, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_suppoRt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
