# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_calculate_dist
#'
#' @description Calculate sum of distances to neighbours
#'
#' @param matrix Matrix with x and y coordinates
#' @param max_dist Maximum distance to consider
#'
#' @details
#' \code{Rcpp} implementation
#'
#' @seealso
#' \code{\link{dist}}
#'
#' @return vector
#'
#' @name rcpp_calculate_dist
#' @export
rcpp_calculate_dist <- function(matrix, max_dist) {
    .Call('_suppoRt_rcpp_calculate_dist', PACKAGE = 'suppoRt', matrix, max_dist)
}

